ifndef CXX
	CXX=clang++
endif
CXXFLAGS+=-std=c++17 -Wall -Wextra -Wpedantic -Werror -fPIC
LDFLAGS+=
LDLIBS+=
MKDIR_P=mkdir -p
RM_RF=rm -rf

SELF_DIR:=$(pwd)

OBJ_DIR=$(SELF_DIR)obj
BIN_DIR=$(SELF_DIR)bin

$(OBJ_DIR):
	$(MKDIR_P) $(OBJ_DIR)

$(BIN_DIR):
	$(MKDIR_P) $(BIN_DIR)

clean:
	$(RM_RF) $(BIN_DIR)
	$(RM_RF) $(OBJ_DIR)

debug: CXXFLAGS += -DDEBUG -g

debug: all

new: clean all
